version: '3.8'

services:
  db:
    image: postgres:14
    container_name: medical_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
    networks:
      - medical-network

  api:
    build: .
    container_name: medical_api
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: db
      DB_PORT: 5432 #Puerto que por defecto toma postgreSQL
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    networks:
      - medical-network

volumes:
  postgres_data:

networks:
  medical-network:
    driver: bridge